# Generated by Django 2.1.7 on 2019-06-10 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Street_add', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('dob', models.DateTimeField(auto_now_add=True)),
                ('Friends', models.ManyToManyField(to='app.Profile')),
                ('company_add', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='app.Address')),
                ('per_add', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='per_address', to='app.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
