# Generated by Django 2.1.7 on 2019-06-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Name',
            field=models.CharField(default='neha', max_length=50),
            preserve_default=False,
        ),
    ]
