# Generated by Django 2.1.7 on 2019-06-12 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190611_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Friends',
            field=models.ManyToManyField(blank=True, null=True, to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_add',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='app.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='per_add',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='per_address', to='app.Address'),
        ),
    ]
